backend:
  name: git-gateway
  branch: master

local_backend: true
publish_mode: editorial_workflow

media_folder: public/assets/img/uploads
public_folder: /assets/img/uploads

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: blog/{{slug}}
    editor:
      preview: false
    fields:
      - name: title
        label: Title
        widget: string
      - name: title_color
        label: Title Color
        widget: color
      - name: title_visible
        label: Title Visible
        widget: string
      - name: author
        label: Author
        widget: string
      - name: category
        label: Category
        widget: string
      - name: created_at
        label: Created At
        widget: date
      - name: excerpt
        label: Excerpt
        widget: string
      - name: thumbnail--xs
        label: Thumbnail Xs
        widget: string
      - name: thumbnail--sm
        label: Thumbnail Sm
        widget: string
      - name: thumbnail--lg
        label: Thumbnail Lg
        widget: string
      - name: thumbnail--xxl
        label: Thumbnail Xxl
        widget: string
      - name: coverImg--xs
        label: Cover Image Xs
        widget: string
      - name: coverImg--sm
        label: Cover Image Sm
        widget: string
      - name: coverImg--lg
        label: Cover Image Lg
        widget: string
      - name: coverImg--xxl
        label: Cover Image Xxl
        widget: string
      - name: body
        label: Body
        widget: markdown
        modes: ['raw']